### PR TITLE
Adjust background and foreground colors

### PR DESCRIPTION
**Pull request by rezonanc**
It seems that dark colors and light colors were swapped. I also double checked this with iTerm2 colors configuration.

The changes reflect direct copy paste from:
https://camo.githubusercontent.com/cdb2f2e986c564b515c0c698e6c45b4ab5d725a9/687474703a2f2f692e696d6775722e636f6d2f776136363678672e706e67

Maybe I'm missing something?

### CODE REVIEW

**Comment by rezonanc** [comment]
Made additional commit to fix the 'tabs_shim' part.
before:
hyper_before
after:
hyper_after

**Comment by mcchrish** [comment]
Ah yes, my color picks are intentionally different. I find the iterm2 colors a bit to dark. However I find the color picks on the vim colorscheme looks just right. Thus I made it look closer to this:
https://camo.githubusercontent.com/2fcf604967167347f15ca8be125d32b18db9bc28/687474703a2f2f692e696d6775722e636f6d2f476b496c38466e2e706e67

Not sure if I want to merge your change, as current users might like what's already there. Perhaps a different colorsheme can be published `hyperterm-gruvbox-dark-alt` (kinda a mouthful)?

**Comment by rezonanc** [comment]
Understood :) No problem. I think I'll create a separate repo for this and implement the light version of it as well (maybe also the contrast options).

**Comment by mcchrish** [comment]
That would be great!
To be honest, hyper hasn't been my terminal of choice lately. Been using iterm2 as it's faster.
Alternatively, you can put up a pull request here making it configurable for users? Kinda like making option to choose light, dark and different shades of contrast?

**Comment by mcchrish** [comment]
But then again, the package should be named `hyper-gruvbox` if that would be the case.

**Comment by rezonanc** [comment]
I always wanted to try out some stuff with javascript, npm and so on... So I gave my first shot: https://www.npmjs.com/package/hyperterm-gruvbox

By the way, regarding iTerm2 performance, strangely I find hyperterm to render much faster compared to iTerm2. That's why I've made the switch! (maybe it's due to some recent optimizations). At least scrolling in vim is much faster (unfortunately a bit more CPU intensive).

**Comment by mcchrish** [comment]
Awesome @rezonanc.
I mentioned your theme in the README for discoverability.

**Pull request closed without merging**
